extend = [
  {path = "rust/riselab/grafana.toml"},
  {path = "rust/riselab/prometheus.toml"},
  {path = "rust/riselab/minio.toml"},
]

[config]
skip_core_tasks = true

[tasks.clean-full]
category = "Misc"
description = "Clean all downloaded binaries by deleting .risingwave folder"
script = '''
#!@duckscript
rm -rf "${PREFIX}"
'''

[tasks.clean-data]
category = "Misc"
description = "Clean all data, config and logs"
script = '''
#!@duckscript
rm -rf "${PREFIX_DATA}"
rm -rf "${PREFIX_LOG}"
rm -rf "${PREFIX_CONFIG}"
'''

[tasks.post-build-risingwave]
category = "RisingWave"
description = "Copy RisingWave binaries to bin"
script = '''
#!@shell
set -e
rm -f "${PREFIX_BIN}/compute-node"
rm -f "${PREFIX_BIN}/meta-node"
ln -s "$(pwd)/rust/target/debug/compute-node" "${PREFIX_BIN}/compute-node"
ln -s "$(pwd)/rust/target/debug/meta-node" "${PREFIX_BIN}/meta-node"
'''

[tasks.build-risingwave]
category = "RisingWave"
description = "Build RisingWave compute-node and meta-node"
script = '''
#!@shell
set -e
cd rust && cargo build
'''

[tasks.build-frontend]
category = "RisingWave"
description = "Build RisingWave frontend"
script = '''
#!@shell
set -e
cd java && ./gradlew build -x test
'''

[tasks.post-build-frontend]
category = "RisingWave"
description = "Post build RisingWave frontend"
script = '''
#!@shell

set -e
rm -f "${PREFIX_BIN}/risingwave-fe-runnable.jar"
ln -s "$(pwd)/java/pgserver/build/libs/risingwave-fe-runnable.jar" "${PREFIX_BIN}/risingwave-fe-runnable.jar"
'''

[tasks.prepare-config]
category = "RiseLAB - Prepare"
description = "Copy necessary configuration files to RiseLAB"
script = '''
#!@shell

set -e

cp "java/pgserver/src/main/resources/logback.xml" "${PREFIX_CONFIG}/logback.xml"
cp "rust/config/log4rs.yaml" "${PREFIX_CONFIG}/log4rs.yaml"
cp "rust/riselab/run_command.sh" "${PREFIX_BIN}/run_command.sh"
cp "rust/riselab/welcome.sh" "${PREFIX_BIN}/welcome.sh"
'''

[tasks.pre-start-playground-development]
category = "RiseLAB - Prepare"
private = true
description = "Prepare playground by downloading necessary tools and build RisingWave"
dependencies = [
  "download-minio",
  "download-mcli",
  "download-grafana",
  "download-prometheus",
  "build-risingwave",
  "post-build-risingwave",
  "build-frontend",
  "post-build-frontend",
  "prepare-config"
]
script = '''
#!@shell

set -e
tmux -V
echo "Note: please make sure tmux version >= 3.2a"
'''

[tasks.pre-start-playground-ci]
category = "RiseLAB - Prepare"
description = "Prepare playground by downloading necessary tools without building RisingWave"
private = true
dependencies = [
  "download-minio",
  "download-mcli",
  "download-grafana",
  "download-prometheus",
  "prepare-config"
]

[tasks.pre-start-playground]
category = "RiseLAB - Prepare"
description = "Prepare playground by downloading necessary tools without building RisingWave"
run_task = [
  { name = "pre-start-playground-development", condition = { profiles = [ "development" ] } },
  { name = "pre-start-playground-ci", condition = { profiles = [ "ci" ] } }
]

[tasks.playground]
alias = "dev"

[tasks.d]
alias = "dev"

[tasks.dev]
category = "RiseLAB - Start"
dependencies = [
  "pre-start-playground"
]
command = "rust/target/debug/playground"
args = ["default"]
description = "Start a RisingWave playground with 1 compute node, 1 meta node, 1 frontend, 1 minio, 1 prometheus"

[tasks.ci-3node]
category = "RiseLAB - Start"
dependencies = [
  "pre-start-playground"
]
command = "rust/target/debug/playground"
args = ["ci-3node"]
description = "Start a RisingWave playground with 3 compute nodes, 1 meta node, 1 frontend"

[tasks.ci-1node]
category = "RiseLAB - Start"
dependencies = [
  "pre-start-playground"
]
command = "rust/target/debug/playground"
args = ["ci-1node"]
description = "Start a RisingWave playground with 1 compute node, 1 meta node, 1 frontend"

[tasks.dev-compute-node]
category = "RiseLAB - Start"
dependencies = [
  "pre-start-playground"
]
command = "rust/target/debug/playground"
args = ["dev-compute-node"]
description = "Start a RisingWave playground with 1 user-managed compute node, 1 meta node, 1 frontend, 1 minio, 1 prometheus"

[tasks.kill-playground]
category = "RiseLAB - Stop"
description = "kill playground"
script = '''
#!@shell
set -e
tmux kill-session -t riselab
'''

[tasks.kill]
alias = "kill-playground"

[tasks.k]
alias = "kill-playground"
