[package]
name = "frontend"
version = "0.1.1"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
clap = { version = "3", features = ["derive"] }
downcast-rs = "1.2"
dyn-clone = "1.0.4"
itertools = "0.10"
log = "0.4"
log4rs = "1"
paste = "1"
risingwave_common = { path = "../common" }
risingwave_sqlparser = { path = "../sqlparser" }
smallvec = { version = "1.6.1", features = ["serde"] }
thiserror = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros", "time", "signal", "fs"] }

[dev-dependencies]
tokio-postgres = "0.7"
