[package]
name = "frontend"
version = "0.1.1"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
clap = { version = "3", features = ["derive"] }
log = "0.4"
log4rs = "1"
risingwave_common = { path = "../common" }
sqlparser = "0.13"
thiserror = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros", "time", "signal", "fs"] }

[dev-dependencies]
tokio-postgres = "0.7"
