[package]
edition = "2018"
name = "risingwave"
version = "0.0.1-SNAPSHOT"

[dependencies]
anyhow = "1"
async-std = {version = "1"}
async-stream = "0.3"
async-trait = "0.1"
backtrace = "0.3"
byteorder = "1"
chrono = "0.4"
clap = "3.0.0-beta.4"
crc32fast = "1"
ctrlc = {version = "3.0", features = ["termination"]}
futures = "0.3"
grpcio = "0.9"
itertools = "0.10"
log = "0.4"
log4rs = "1"
num-traits = "0.2"
paste = "1"
pb-construct = {path = "../utils/pb-construct"}
pb-convert = {path = "../utils/pb-convert"}
pb-convert-derive = {path = "../utils/pb-convert-derive"}
protobuf = "2"
rayon = "1"
risingwave-proto = {path = "../proto"}
rust_decimal = "1"
rust_decimal_macros = "1"
serde_json = "1"
serde_with = "1"
serde = { version = "1", features = ["derive"] }
smallvec = "1"
thiserror = "1"
tokio = {version = "1", features = ["rt", "rt-multi-thread", "sync", "macros", "time"]}
twox-hash = "1"
typed-builder = "0.9"
rdkafka = { version = "0.25", features = ["cmake-build"] }
lazy_static = "1.4.0"

[dev-dependencies]
approx = "0.5"

[[bin]]
name = "compute-node"
path = "src/bin/compute_node.rs"

[build-dependencies]
protoc-grpcio = "3"
