[package]
name = "risingwave"
version = "0.0.1-SNAPSHOT"
edition = "2018"

[dependencies]
log4rs = "1"
grpcio = "0.9"
protobuf = "2"
futures = "0.3"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync"] }
rayon = "1"
thiserror = "1"
backtrace = "0.3"
log = "0.4"
risingwave-proto = { path = "../proto" }
anyhow = "1"
typed-builder = "0.9"
ctrlc = { version = "3.0", features = ["termination"] }
pb-convert-derive = { path = "../utils/pb-convert-derive" }
pb-convert = { path = "../utils/pb-convert" }
async-trait = "0.1"
serde_json = "1"
chrono = "0.4"
clap = "3.0.0-beta.4"
rust_decimal = "1"
rust_decimal_macros = "1"

[[bin]]
name = "compute-node"
path = "src/bin/compute_node.rs"

[build-dependencies]
protoc-grpcio = "3"
