[package]
name = "risingwave"
version = "0.0.1-SNAPSHOT"
edition = "2018"

[dependencies]
log4rs = "1.0.0"
grpcio = "0.9.0"
protobuf = "2.24.1"
futures = "0.3.16"
tokio = { version = "1.9.0", features = ["rt", "rt-multi-thread", "sync"]}
rayon = "1.5.1"
thiserror = "1.0"
backtrace = "0.3.61"
log = "0.4"
risingwave-proto = {path = "../proto"}
protobuf-convert = "0.4.0"
anyhow = "1.0.42"
typed-builder = "0.9.0"
ctrlc = { version = "3.0", features = ["termination"] }

[[bin]]
name = "compute-node"
path = "src/bin/compute_node.rs"

[build-dependencies]
protoc-grpcio = "3.0.0"
