name: Protobuf CI

on:
  pull_request:
    branches: [ main ]
    types: [ opened ]
    paths:
      - 'proto/**'

jobs:
  protobuf-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          apt install -y protobuf-compiler

      - name: Install prototool
        run: |
          curl -sSL \
            https://github.com/uber/prototool/releases/download/v1.8.0/prototool-$(uname -s)-$(uname -m).tar.gz | \
            tar -C /usr/local --strip-components 1 -xz

      - name: Code Format
        run: |
          prototool format -d

      - name: Install buf
        run: |
          # Substitute PREFIX for your install prefix.
          # Substitute VERSION for the current released version.
          PREFIX="/usr/local" && \
          VERSION="1.0.0-rc6" && \
            curl -sSL \
              "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m).tar.gz" | \
              tar -xvzf - -C "${PREFIX}" --strip-components 1

      - name: Run Linter
        run: |
          buf lint
