[package]
edition = "2018"
name = "pb-construct"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0"

[dev-dependencies]
protobuf = "2.25.0"

[build-dependencies]
protoc-rust = "2.25.0"
