[package]
edition = "2021"
name = "risingwave-pb"
version = "0.1.0"

[dependencies]
bytes = "1"
prost = "0.8"
prost-helpers = { path = "helpers" }
prost-types = "0.8"
tonic = "0.5"

[build-dependencies]
convert_case = "0.4"
prost = "0.8"
prost-types = "0.8"
quote = "1"
tonic-build = "0.5"
