[package]
edition = "2021"
name = "risingwave-pb"
version = "0.1.0"

[dependencies]
bytes = "1"
prost = "0.8"
prost-helpers = { path = "helpers" }
prost-types = "0.8"
protobuf = "2"
risingwave-proto = { path = "../proto" }
tonic = "0.5"

[build-dependencies]
tonic-build = "0.5"
