extend = "common.toml"

[env]
GRAFANA_ARCH = "${ARCH}"
GRAFANA_DOWNLOAD_PATH = "${PREFIX_TMP}/grafana.tar.gz"
GRAFANA_VERSION = "8.3.3"
GRAFANA_RELEASE = "grafana-${GRAFANA_VERSION}"
GRAFANA_DOWNLOAD_TAR_GZ = "https://dl.grafana.com/oss/release/${GRAFANA_RELEASE}.${GRAFANA_ARCH}.tar.gz"

[tasks.download-grafana]
category = "RiseLAB"
dependencies = ["prepare"]
description = "Download and extract Grafana"
script = '''
#!@shell
set -e
if [ -d "${PREFIX_BIN}/grafana" ]; then
    exit 0
fi
echo "Grafana not found, download ${GRAFANA_RELEASE}"
wget -O "${GRAFANA_DOWNLOAD_PATH}" "${GRAFANA_DOWNLOAD_TAR_GZ}"
tar -xf "${GRAFANA_DOWNLOAD_PATH}" -C "${PREFIX_TMP}"
mv "${PREFIX_TMP}/${GRAFANA_RELEASE}" "${PREFIX_BIN}/grafana"
rm "${GRAFANA_DOWNLOAD_PATH}"
'''

[tasks.run-grafana]
category = "RiseLAB"
dependencies = ["download-grafana"]
description = "Run Grafana"
