[tasks.configure-if-not-configured]
condition = { env_not_set = [ "RISELAB_CONFIGURED" ] }
script = '''
#!@shell
set -e
ENV_PATH="$(pwd)/riselab-components.user.env"
cd rust && cargo run --bin riselab-config -- "${ENV_PATH}" --default
'''

[tasks.configure]
script = '''
#!@shell
set -e
ENV_PATH="$(pwd)/riselab-components.user.env"
cd rust && cargo run --bin riselab-config -- "${ENV_PATH}"
'''
