[workspace]
members = [
  "batch",
  "common",
  "metadata",
  "prost",
  "prost/helpers",
  "proto",
  "server",
  "stream",
  "utils/pb-construct",
  "utils/pb-convert",
  "utils/pb-convert-derive",
]
