[workspace]
members = [
  "batch",
  "common",
  "meta",
  "prost",
  "prost/helpers",
  "proto",
  "server",
  "storage",
  "stream",
  "tests/regress",
  "utils/memcomparable",
  "utils/pb-construct",
  "utils/pb-convert",
  "utils/pb-convert-derive",
]

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'
