[workspace]
members = [
  "batch",
  "common",
  "meta",
  "prost",
  "prost/helpers",
  "proto",
  "server",
  "stream",
  "tests/regress"
,
  "utils/memcomparable",
  "utils/pb-construct",
  "utils/pb-convert",
  "utils/pb-convert-derive"]
