[package]
name = "risingwave_common"
version = "0.1.0-SNAPSHOT"
edition = "2021"

[dependencies]
anyhow = "1"
async-std = { version = "1" }
async-stream = "0.3"
async-trait = "0.1"
backtrace = "0.3"
byteorder = "1"
bytes = "1"
chrono = "0.4"
clap = "3.0.0-beta.5"
clap_derive = "3.0.0-beta.5"
crc32fast = "1"
ctrlc = { version = "3.0", features = ["termination"] }
either = "1"
futures = "0.3"
itertools = "0.10"
lazy_static = "1.4.0"
log = "0.4"
log4rs = "1"
num-traits = "0.2"
paste = "1"
pb-construct = { path = "../utils/pb-construct" }
pb-convert = { path = "../utils/pb-convert" }
pb-convert-derive = { path = "../utils/pb-convert-derive" }
prost = "0.8"
protobuf = "2"
protobuf-codegen-pure = "2.25.2"
rdkafka = { version = "0.25", features = ["cmake-build"] }
risingwave-pb = { path = "../prost" }
risingwave-proto = { path = "../proto" }
rust_decimal = "1"
rust_decimal_macros = "1"
serde = { version = "1", features = ["derive"] }
serde-protobuf = "0.8.2"
serde-value = "0.7.0"
serde_json = "1"
serde_with = "1"
smallvec = "1"
tempfile = "3.2.0"
thiserror = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros", "time", "signal"] }
tokio-stream = "0.1.7"
tonic = "0.5"
twox-hash = "1"
typed-builder = "0.9"

[dev-dependencies]
approx = "0.5"
assert_matches = "1.5"
rand = "0.8"
