# Note: this configuration file is not used actually

[server]
heartbeat_interval = 100

[olap]
chunk_size = 1024

[streaming]
chunk_size = 1024

[hummock]
sst_size = 268435456 # 256MB
block_size = 65536 # 64KB
