[package]
edition = "2021"
name = "pb-convert-derive"
version = "0.1.0"

[lib]
name = "pb_convert_derive"
proc-macro = true

[dependencies]
anyhow = "1"
darling = "0.13"
pb-convert = { path = "../pb-convert" }
phf = { version = "0.10", features = ["macros"] }
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
thiserror = "1"

[dev-dependencies]
protobuf = "2"

[build-dependencies]
protoc-rust = "2"
