[package]
name = "pb-convert-derive"
version = "0.1.0"
edition = "2018"

[lib]
name = "pb_convert_derive"
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
proc-macro2 = "1.0.28"
thiserror = "1.0"
anyhow = "1.0"
phf = { version = "0.10.0", features= ["macros"] }
darling = "0.13"
pb-convert = {path = "../pb-convert"}

[dev-dependencies]
protobuf = "2.25.0"

[build-dependencies]
protoc-rust = "2.25.0"