name: PR Checklist

on:
  pull_request:
    branches: [ main ]
    types: [opened]

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: checklist job
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Checklist
        uses: fuyufjh/contextual-qa-checklist-action@master
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          input-file: .github/checklist.yml
          show-paths: false
          comment-header: "Great PR! Please check the following items before merging:"
          comment-footer: ""
